### ISSUE TITLE
麻烦各位测试一下！

### ISSUE THREAD

**Issue by lkeme** [lkeme/BiliHelper#12]
刚才代码好像回退错了一个版本，我也忘记哪里修改了，有问题，反馈我！

**Comment by Cettiidae** [comment]
脚本运行中会有这种东西，请问是bug吗？还是设计如此？
不过真的很好用哦～
`
2018-03-19 23:36:58] [SOCKET] PCActive: 【林发发爱林小兔】在直播间【3151254】洒下 漫天花雨，快来拾撷桃花，邂逅你的缘分！
array(4) {
  ["code"]=>
  int(0)
  ["msg"]=>
  string(12) "加入成功"
  ["message"]=>
  string(12) "加入成功"
  ["data"]=>
  array(7) {
    ["raffleId"]=>
    string(5) "21591"
    ["roomid"]=>
    string(7) "3151254"
    ["type"]=>
    string(11) "flower_rain"
    ["from"]=>
    string(21) "林发发爱林小兔"
    ["face"]=>
    string(74) "https://i1.hdslb.com/bfs/face/9146f1f1a16530caff0e4ea78f607a087d7bc26a.jpg"
    ["time"]=>
    string(10) "1521473811"
    ["status"]=>
    int(2)
  }
`

**Comment by lkeme** [comment]
@CN-Lyc 这并不是bug哦，只是还在处于开发阶段，有些打印数据我都还没删而已，以后会删掉的

**Comment by suohun** [comment]
自动投喂出错，重新运行也出错；另个号之前版本的是自动赠送成功，不知道是不是，今天第一次用这个功能
![qq 20180319234803](https://user-images.githubusercontent.com/37374632/37606472-802df4cc-2bd0-11e8-991f-561ab79fd9c5.png)

**Comment by zvrh** [comment]
在每个心跳包后面会提示一个“CMD: 数据包不全或有新的类型”，例如：
```
[2018-03-20 08:11:09] [心跳] SocketHeart: OK!
[2018-03-20 08:11:09] [SOCKET] CMD: 数据包不全或有新的类型]
```

**Comment by Dkw346456741** [comment]
建议cookies刷新时间12小时或8小时之类的，这样可以每天固定时间刷新

**Comment by lkeme** [comment]
@suohun 关于自动投喂，我还在测试，估计有可能是api或者参数的变动

**Comment by lkeme** [comment]
@zegzhi 这不是bug，只是偷懒了，少写了个判断

**Comment by lkeme** [comment]
@Dkw346456741 cookie问题还在研究，(B站的cookie好像是不能维持活跃的，就算自己刷新了，到了时间也会断掉) ,这个搞清楚了才好设置周期，不过另说啊12小时或者8小时是不是太短，我现在默认的20个小时

**Comment by lkeme** [comment]
@suohun 已修复

**Comment by suohun** [comment]
@lkeme 硬币兑换功能出错【昨天外挂前的版本是正常的】
![qq 20180320171053](https://user-images.githubusercontent.com/37374632/37645454-db5cf62c-2c61-11e8-8ba1-731076095861.png)

**Comment by lkeme** [comment]
@suohun 什么时候的版本,我今天修过一次的

**Comment by suohun** [comment]
@lkeme 0.94 应该是18号的

**Comment by lkeme** [comment]
@suohun 我修bug都没改版本号，只有添加功能才改的

**Comment by suohun** [comment]
@lkeme 就是今天下的最新版本会出错

**Comment by lkeme** [comment]
@suohun = =什么时候下的，我下午1点左右修的，我刚才才测试了一次，没问题啊

**Comment by suohun** [comment]
@lkeme 抱歉，我复制错了，解压到昨天下的了-_-!
