### ISSUE TITLE
遇到些小麻烦，持续运行一天左右之后会报错不再刷新信息

### ISSUE THREAD

**Issue by devilrock111** [lkeme/BiliHelper#13]
同时也不再参加抽奖，我忘了截图遇到两次了，配合systemd使用的，但是重启systemd的service后又会回复正常隔一天之后又会这样

**Comment by lkeme** [comment]
@devilrock111 是什么错误，
是这个错误吗
![9cew 9 n 3r400 c 11ayh](https://user-images.githubusercontent.com/19500576/37637316-ed434b40-2c41-11e8-86fc-c80f2d44f2f8.png)

**Comment by suohun** [comment]
@lkeme 你截图这个我今天也出现了，然后我删除user文件夹，重新运行就好了，是cookies的原因？

**Comment by lkeme** [comment]
@suohun - -粗心引起的问题，已经修好了

**Comment by devilrock111** [comment]
对对对。。。就是截图那张

**Comment by lkeme** [comment]
@devilrock111 下最新的，已经修复了

**Comment by devilrock111** [comment]
之前的油猴脚本都关停了，不知道这次能坚持多久
