### ISSUE TITLE
是否会有封号风险呢

### ISSUE THREAD

**Issue by Cettiidae** [lkeme/BiliHelper#14]
一天能撸到1.5k根辣条，真的太丧心病狂了
查阅了一下bilibili的一些条文好像没见相关说明，有没有挂了很久的大佬来说说。
🌚😂不过还是要赞美作者和原仓库，太强了

**Comment by devilrock111** [comment]
tb有人收费挂机了，看介绍应该这份是

**Comment by czp3009** [comment]
为什么我抽一天的小电视也只能抽到200根, 难道说, 这就是, 欧皇.

ORZ

**Comment by Cettiidae** [comment]
@czp3009 或许要看看有没有绑定手机号实名验证啥的？而且能抽到辣条的不仅仅有小电视啊，最近那个桃花的活动也能抽hhh
或许是撸的人多了，难抢🌚

**Comment by czp3009** [comment]
@CN-Lyc #(滑稽)

**Comment by lkeme** [comment]
@czp3009 吃鲸，你居然跑我这来玩了 @CN-Lyc 表情是怎么发的

**Comment by Cettiidae** [comment]
@lkeme  就是普通的emoji😁👌直接打出来就好了
