### ISSUE TITLE
APPActive: 访问被拒绝

### ISSUE THREAD

**Issue by Cettiidae** [lkeme/BiliHelper#15]
其他弹幕什么的都能正常读取，但是抽奖都不行了

**Comment by lkeme** [comment]
@CN-Lyc  太频繁 ，被ban了，我3个号，也被ban了一个，好像时效性的，会恢复，我会尝试找解决办法的

**Comment by Cettiidae** [comment]
@lkeme 怪不得，我还以为bilibili真的给为所欲为那么久23333，拿小号挂算了

**Comment by czp3009** [comment]
我想，需要加入一些随机延迟，抽奖一出来马上就去抽，这个显然不是人力能做到的，服务端可能有一些反脚本机制，然后就被ban了

**Comment by zvrh** [comment]
发现很多人都是晚上3点多一点被ban的，次日0点解封。
可以尝试写个计划任务，2点关脚本6点再重新打开。

**Comment by lkeme** [comment]
@zegzhi 3点  6点这么精准的数据怎么来的 ，0点解封我是知道的，只ban一天

**Comment by zvrh** [comment]
@lkeme 在record目录不是有日志吗，领取失败就是被ban的时间。
另外我也加了一个b站直播相关的群，他们也是显示3点20分左右被ban的。
至于6点就看自己情况随便设置，反正晚上也没多少礼物。

**Comment by lkeme** [comment]
@zegzhi 惊了，还真是，特地去看下了日志，确实是3:20左右

**Comment by lkeme** [comment]
@zegzhi o了 加了个睡觉

**Comment by zvrh** [comment]
今天12:12有一波封号，B站已经开始重视脚本问题，感觉以后要凉了。

**Comment by lkeme** [comment]
@zegzhi 这不是我想的问题，我只能说尽可能的了解封号机制，尽可能的做些避免封号的措施

**Comment by Cettiidae** [comment]
继APPActive后。。。宝箱也被封了的我，是不是宝箱计算好小学数学后也随机延迟领取一下？

**Comment by lkeme** [comment]
@CN-Lyc  宝箱应该是背了活动抽奖的锅，宝箱应该是不用的，被ban了同时会有好几个api不能访问的，更新了一个规避措施 ，不知道能不能行得通

**Comment by lkeme** [comment]
@CN-Lyc @zegzhi 
 
凌晨恢复的话，可以尝试下最新的版本。是最新的这个提交

**Comment by czp3009** [comment]
什么, 要封号了, 那黄了, 本来我还想做一个 Bilibili 云挂机平台的.....
