### ISSUE TITLE
挂一段时间之后参加还是自动参加开宝箱也开，但是直播不签到了

### ISSUE THREAD

**Issue by devilrock111** [lkeme/BiliHelper#16]
顺便问下路由每天设置自动重启，脚本不工作的解决方式。

**Comment by lkeme** [comment]
@devilrock111 我没太看懂，什么意思啊，是签到失效了吗？不过我刚才测试了一下，都能正常签到的。另外，自动重启的话，你可以尝试一下，readme的高级部分，当然我也不知道路由器能不能用

**Comment by suohun** [comment]
@lkeme 借楼，好像是有这个问题，不会自动签到和领取双端这些日常任务，每天得重新运行才会执行一遍。
还有个问题，不知道能不能实现断网后重启的功能。

**Comment by lkeme** [comment]
@suohun  不会吧，应该不会这样的,我测试一天左右再说，这个问题先保留吧
另外断网重启？上面的是重启路由器，你只能弄开机自启

**Comment by suohun** [comment]
@lkeme 2333,估计是同个意思，就是网络断开后脚本停止工作，但是网络恢复后脚本不会自动启动执行，得手动重新启动。他路由器那个应该也是说的这个问题

**Comment by T-Evan** [comment]
附议

**Comment by lkeme** [comment]
@tangmingshuai 附议什么鬼啊 @suohun 他的是路由器重启，就和电脑开关机一样，只有尝试开机自启

**Comment by suohun** [comment]
噢，那就不一样了，不是开机自启的问题，我是有时候网不稳定断了一两分钟又恢复了，但是脚本停止工作了，网络恢复后也不会继续执行，得重新运行脚本。

**Comment by devilrock111** [comment]
前两天没空上，没来及回复抱歉，跟3L情况基本一致，因为脚本是在树莓派上运行的，路由设置每天自动重启，重启时候因为网络断开没法工作，但是网络恢复后脚本也不会继续运行
