### ISSUE TITLE
[宝箱] 访问被拒绝

### ISSUE THREAD

**Issue by huiyadanli** [lkeme/BiliHelper#17]
我挂了两个号只有自己的号出现这个问题。。。

宝箱领取不了了，疑似被BAN。。。自己在页面上手动领取也提示访问被拒绝。。

**Comment by Newchana** [comment]
消停一天 然后换新版本脚本

**Comment by huiyadanli** [comment]
昨天小电视自动抽奖也被BAN了。都是消停几小时就好了。。
