### ISSUE TITLE
重复抽奖

### ISSUE THREAD

**Issue by colorsakura** [lkeme/BiliHelper#18]
当同时有多个小电视时，就会重复抽奖

**Comment by lkeme** [comment]
@colorsakura 你是用的最新版本吗  ？能不能配个图？我应该已经过滤了重复抽奖的，你配个图，我定位下问题，谢谢

**Comment by colorsakura** [comment]
@lkeme  是最新版，我今天晚上看看能不能截图，昨天的小电视挺多的

**Comment by colorsakura** [comment]
@lkeme 
![screenshot from 2018-03-31 13-13-54](https://user-images.githubusercontent.com/32534829/38159910-b70d427c-34e5-11e8-80eb-e3fbe0262ec1.png)
这是日志截图

**Comment by lkeme** [comment]
@colorsakura 这些是已经过滤过的，重复抽奖我打的提示，但是实际上并没有抽奖
