### ISSUE TITLE
家里网络不稳定有时候会断网几分钟，脚本在断网后不会继续工作。

### ISSUE THREAD

**Issue by devilrock111** [lkeme/BiliHelper#19]
树莓派运行脚本systemd监视，出现断网的话目前只能手动sudo systemctl restart bilibili.service这样子，有其他可靠的方法可以介绍么。

**Comment by zvrh** [comment]
写个守护脚本，在检测到断网重连后重启 bilibili.service 。

**Comment by devilrock111** [comment]
没liunx基础只能走一步看一步了，但是用法都是慢慢研究的

好吧，大概知道了crontab可以实现，我琢磨下

**Comment by zvrh** [comment]
可以参考一下这个：http://www.cnblogs.com/liyufeng2013/p/6419385.html

**Comment by devilrock111** [comment]
谢谢了我去看看
