### ISSUE TITLE
找不到autoload.php（已解决）

### ISSUE THREAD

**Issue by rhjdvsgsgks** [lkeme/BiliHelper#23]
PHP Warning:  require(vendor/autoload.php): failed to open stream: No such file or directory in /root/BiliHelper/index.php on line 15
PHP Fatal error:  require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/local/php/lib/php') in /root/BiliHelper/index.php on line 15

**Comment by lkeme** [comment]
直接克隆的或者下载的请注意仔细readme的使用说明

**Comment by rhjdvsgsgks** [comment]
@lkeme 已经好了，谢谢，顺便问一下UID是干什么用的，该怎么填？

**Comment by lkeme** [comment]
UID 默认就好了

**Comment by dulongxiang** [comment]
> PHP Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in /root/BiliHelper/index.php on line 15
> PHP Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/local/php/lib/php') in /root/BiliHelper/index.php on line 15



> @lkeme 已经好了，谢谢，顺便问一下UID是干什么用的，该怎么填？

请问怎么解决的，按照readme也不行 哪里出错了

**Comment by rhjdvsgsgks** [comment]
好像是`composer install`一下就好了

**Comment by dulongxiang** [comment]
> 好像是`composer install`一下就好了

弄好了 把vendor复制进去就好了hhh
