### ISSUE TITLE
目前版本小电视功能已失效

### ISSUE THREAD

**Issue by ZeusGamingPlay** [lkeme/BiliHelper#26]
抓包发现目前B站有小电视蜜罐机制，发送假包导致无法正常领取小电视，同时已出现挂机账号被封的情况！
脚本会定时崩溃，Debug信息如下：
#0 /home/ownAccount/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/ownAccount/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/ownAccount/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /home/ownAccount/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28):  in /home/ownAccount/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 185

PHP5.6 Centos6.9（Final）

**Comment by rhjdvsgsgks** [comment]
同
