### ISSUE TITLE
nohup 运行长时间后 cpu 吃满

### ISSUE THREAD

**Issue by crazymingming** [lkeme/BiliHelper#28]
我用nohup 运行 的，命令如下 
nohup php index.php &   
然后机器里挂了2 个签到是在不同的文件夹的 一个在文件夹A 一个在文件夹B，每次都是先cd 过去执行上面的命令的。
Php版本 7.2
长时间运行后 就会其中一个进程吃满单个U 线程，再过一段时间后就输出停止，nohup.out 也无新的输出，签到也停止了。

**Comment by NeverBehave** [comment]
@crazymingming 如果是没有小电视的版本，我们这里104个实例运行了2个月没有任何问题

**Comment by crazymingming** [comment]
请问你用的是0.0.3 beta 这个版本的么，而且也是nohup 运行的么

**Comment by NeverBehave** [comment]
@crazymingming 原版，使用screen
