### ISSUE TITLE
无法运行超过一天时间

### ISSUE THREAD

**Issue by ZeusGamingPlay** [lkeme/BiliHelper#36]
PHP报错如下
`PHP Fatal error:  Uncaught Error: Class 'Wrench\Client' not found in /home/bs/src/Websocket.php:45
Stack trace:
#0 /home/bs/src/Websocket.php(32): lkeme\BiliHelper\Websocket::init()
#1 /home/bs/index.php(63): lkeme\BiliHelper\Websocket::run()
#2 /home/bs/index.php(101): lkeme\BiliHelper\Index::run('user1.conf')
#3 {main}
  thrown in /home/bs/src/Websocket.php on line 45`

**Comment by lkeme** [comment]
缺个东西，用composer安装

**Comment by ZeusGamingPlay** [comment]
fixed.
THX!
