### ISSUE TITLE
Stopped after a period of time

### ISSUE THREAD

**Issue by caesarw** [lkeme/BiliHelper#37]
## What I should see
BiliHelper script running normally.

## What I saw
BiliHelper stopped running after a period time (in my case two days of continuous running) and I've got a BiliHelper and PHP debug output.  

BiliHelper output:  

```
[2018-08-24 21:38:52] Bilibili.DEBUG: WS_OP_MESSAGE (len=295)
 [] []
[2018-08-24 21:38:54] Bilibili.DEBUG: WS_OP_MESSAGE (len=1304
) [] []
[2018-08-24 21:38:56] Bilibili.DEBUG: WS_OP_MESSAGE (len=243)
 [] []
[2018-08-24 21:38:58] Bilibili.DEBUG: WS_OP_MESSAGE (len=1306
) [] []
```

PHP debug output:

```
PHP Fatal error:  Allowed memory size of 134217728 bytes exha
usted (tried to allocate 1052672 bytes) in /pathto/BiliHelper/vendor/wrench/wrench/lib/Wrench/Client.php on lin
e 145
```

Looks like something is wrong with wrench library. I'm using the latest composer installation so in my case wrench library should be the latest.

Thanks for helping! 😁😁

**Comment by lkeme** [comment]
这个问题我已经知道了，由于不好复现，目前还在定位中
