### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by xxhh283** [lkeme/BiliHelper#4]
使用 Wampserver32 运行后

[37m[2018-03-14 02:00:20] [BiliLogin] 加载账号密码[0m [32m[2018-03-14 02:00:20] [BiliLogin] 加载成功,获取加密信息[0m 

( ! ) Fatal error: Call to undefined function openssl_pkey_get_public() in D:\wamp\www\BiliHelper-master\includes\BiliLogin.php on line 218
--

1 | 0.0003 | 136616 | {main}( ) | ...\index.php:0
2 | 0.0037 | 486416 | BiliLogin->start( ) | ...\index.php:18
3 | 0.1286 | 487584 | BiliLogin->rsaEncrypt( ) | ...\BiliLogin.php:46

**Comment by Franinc** [comment]
没有安装php的openssl扩展

**Comment by lkeme** [comment]
@xxhh283 如楼上所说，缺少`openssl`拓展

**Comment by xxhh283** [comment]
@Franinc @lkeme  已可以使用，感谢
