### ISSUE TITLE
抽取礼物提示你已经领取过了

### ISSUE THREAD

**Issue by KyuubiRan** [lkeme/BiliHelper#43]
为什么会这样emmmm
https://i.loli.net/2018/12/11/5c0fa93a03787.png

**Comment by KyuubiRan** [comment]
是今天刚更新到0.0.8发生的emmmm 然后更新完后辣条一个都抽不到了。。

**Comment by lkeme** [comment]
你是不是短时间内重新启动过

**Comment by lkeme** [comment]
嗨翻全城什么都辣条领不到的话尝试修改配置里的atuo keys  改为false

**Comment by KyuubiRan** [comment]
看一下那个截图emmmm 所有东西都领不了了…挂着辣条一个下午没加emmmm 我重新copy了一份配置文件并修改了 也把autokeys改成false的 还是无效

**Comment by KyuubiRan** [comment]
已经恢复了   删除了那个.user.conf.swp 重新改了一下权限好像好了
