### ISSUE TITLE
访问被拒绝

### ISSUE THREAD

**Issue by KyuubiRan** [lkeme/BiliHelper#44]
这是被ban了吗 大概多久恢复。。。两个号都GG了
建议跟那个谷歌浏览器的插件一样 加一个礼物丢失率 不要每个都领 这个几率自己调就好了 然后计划任务也弄成自己可以选时间段的…

**Comment by KyuubiRan** [comment]
目前已经过了一个星期了还是凉凉。。

**Comment by lkeme** [comment]
封禁时间大概是7的倍数，丢弃率的话有这个备忘了
