### ISSUE TITLE
好像绑定了手机如果出现验证无法登录挂机

### ISSUE THREAD

**Issue by Yakumo-Yukari** [lkeme/BiliHelper#45]
好像绑定了手机如果出现验证无法登录挂机

**Comment by lkeme** [comment]
抱歉，我没看懂你的问题意思

**Comment by Yakumo-Yukari** [comment]
> 抱歉，我没看懂你的问题意思

emmm  就是账号如果绑定了手机 如果异地登录有可能会出现安全问题 就会提示验证手机验证码   在VPS上就无法登录

**Comment by lkeme** [comment]
这是正常的哦，一般新绑定手机账号有异常行为，比如异地登录什么的，很大几率有验证，不是脚本问题，是B站的风控策略

**Comment by rhjdvsgsgks** [comment]
可以挂服务器的代理反复登录几次，好像能减少这种情况出现

**Comment by Yakumo-Yukari** [comment]
> 可以挂服务器的代理反复登录几次，好像能减少这种情况出现



> 这是正常的哦，一般新绑定手机账号有异常行为，比如异地登录什么的，很大几率有验证，不是脚本问题，是B站的风控策略

谢谢回复  我试试看
