### ISSUE TITLE
请问能否实现，在指定房间定时发送弹幕的功能

### ISSUE THREAD

**Issue by T-Evan** [lkeme/BiliHelper#5]
RT

**Comment by lkeme** [comment]
@tangmingshuai 这功能倒是很好实现，但是感觉并没有多大用处

**Comment by T-Evan** [comment]
恩恩，了解了

**Comment by lkeme** [comment]
@tangmingshuai  已添加一个自定义发送弹幕的功能，详情呢，你可以看下README的FAQ部分，你可以先测试一下，有问题就告知我
