### ISSUE TITLE
是否有办法关闭日志或指定日志输出方式？

### ISSUE THREAD

**Issue by Sucareto** [lkeme/BiliHelper#50]
用 systemd 启动，日志被塞爆...
在 user.conf 里面发现有写入日志的选项，
那是否写入了日志文件了以后就不会在 systemd 日志输出了呢....

**Comment by lkeme** [comment]
配置文件里的记录日志是独立功能的，和你其他方式启动程序，或者其他方式保存日志都是互不影响的
