### ISSUE TITLE
关闭自动送礼，和自动兑换硬币功能咋操作请问。。

### ISSUE THREAD

**Issue by lovezm** [lkeme/BiliHelper#6]
是不是注释掉index.php的就可以关闭自动送礼？
$api->roomid = 189;

**Comment by lkeme** [comment]
@lovezm 已添加一个跳过任务 ，把你需要的两个任务都添加了，看README的FAQ部分，你可以先测试一下，如果有新问题就issue好吧，没问题的话就随手close掉这个issue
