### ISSUE TITLE
Fatal error: Allowed memory size of exhausted 

### ISSUE THREAD

**Issue by xxhh283** [lkeme/BiliHelper#7]
不定时出现
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 976302113 bytes) in D:\wamp\www\BiliHelper-master\includes\Traits\socketHelper.php on line 132
Call Stack
#	Time	Memory	Function	Location
1	0.0004	136856	{main}( )	...\index.php:0
2	0.3507	489416	call_user_func:{D:\wamp\www\BiliHelper-master\index.php:43} ( )	...\index.php:43
3	0.3507	489512	start( )	...\index.php:43
4	0.3507	498712	Bilibili->run( )	...\index.php:40
5	6589.7937	503248	Bilibili->customerAction( )	...\Bilibili.php:166
6	6589.7937	503248	Bilibili->socketHelperStart( )	...\Bilibili.php:427
7	6589.7937	503248	Bilibili->decodeMessage( )	...\socketHelper.php:43
8	6589.7937	503576	socket_read ( )	...\socketHelper.php:132

**Comment by lkeme** [comment]
@xxhh283 这个报错是挂了多久出现的，是报完错就退出了还是在继续执行？

**Comment by xxhh283** [comment]
@lkeme 时间不定，有时2小时，有时十几分，报错后停止运行

**Comment by xxhh283** [comment]
较新的一次
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 808484206 bytes) in D:\wamp\www\BiliHelper-master\includes\Traits\socketHelper.php on line 132
--


Call Stack
--


# | Time | Memory | Function | Location
1 | 0.0004 | 136616 | {main}( ) | ...\index.php:0
2 | 0.3436 | 495960 | call_user_func:{D:\wamp\www\BiliHelper-master\index.php:43} ( ) | ...\index.php:43
3 | 0.3436 | 496056 | start( ) | ...\index.php:43
4 | 0.3437 | 505664 | Bilibili->run( ) | ...\index.php:40
5 | 818.2400 | 509688 | Bilibili->customerAction( ) | ...\Bilibili.php:146
6 | 818.2400 | 509688 | Bilibili->socketHelperStart( ) | ...\Bilibili.php:397
7 | 818.2400 | 509688 | Bilibili->decodeMessage( ) | ...\socketHelper.php:43
8 | 818.2400 | 510000 | socket_read ( ) | ...\socketHelper.php:132

**Comment by xxhh283** [comment]
另外出现了这个 可以继续运行

Warning: unpack(): Type N: not enough input, need 4, have 3 in D:\wamp\www\BiliHelper-master\includes\Traits\socketHelper.php on line 124
--


# | Time | Memory | Function | Location


1 | 0.0005 | 136648 | {main}( ) | ...\index1.php:0
2 | 1.2763 | 496040 | call_user_func:{D:\wamp\www\BiliHelper-master\index1.php:43} ( ) | ...\index1.php:43
3 | 1.2763 | 496136 | start( ) | ...\index1.php:43
4 | 1.2764 | 505744 | Bilibili->run( ) | ...\index1.php:40
5 | 60.6001 | 509384 | Bilibili->customerAction( ) | ...\Bilibili.php:146
6 | 60.6002 | 509384 | Bilibili->socketHelperStart( ) | ...\Bilibili.php:397
7 | 60.6006 | 509368 | Bilibili->decodeMessage( ) | ...\socketHelper.php:43
8 | 60.6006 | 509544 | unpack ( ) | ...\socketHelper.php:124

**Comment by lkeme** [comment]
@xxhh283 我今天下午在本机挂了一下午，并没有复现你这个问题，我会继续排查，

如果有需要，你可以暂时先调整一下php.ini的memory_limit，

另外，可以说下你是什么环境，什么版本，什么方式运行的吗

**Comment by xxhh283** [comment]
@lkeme 
win8.1 64位
Wampserver 1.6.2.37
整合了 PHP 5.6.25 mysql 5.7.14 apche 2.4.23

然后用chrome  64.0.3282.119 运行

**Comment by lkeme** [comment]
@xxhh283 如果可能，你可以换个php7.*+的版本测试一下

**Comment by xxhh283** [comment]
@lkeme 

现用Wampserver 64位 3.1.0 测试中
php 7.0.23
mysql 5.7.19 
apche 2.4.27
内存改到1G

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 1869376632 bytes) in D:\wamp64\www\BiliHelper-master\includes\Traits\socketHelper.php on line 152

# |  Time |  Memory |  Function |  Location

1 | 0.0004 | 370840 | {main}( ) | ...\index.php:0
2 | 1.1949 | 801264 | start( ) | ...\index.php:43
3 | 1.1950 | 809816 | Bilibili->run( ) | ...\index.php:40
4 | 212.8516 | 816512 | Bilibili->customerAction( ) | ...\Bilibili.php:154
5 | 212.8516 | 816512 | Bilibili->socketHelperStart( ) | ...\Bilibili.php:414
6 | 212.8517 | 816512 | Bilibili->decodeMessage( ) | ...\socketHelper.php:48
7 | 212.8517 | 816936 | socket_read ( ) | ...\socketHelper.php:152

**Comment by lkeme** [comment]
= =用终端啊 这是终端的

不是用浏览器，直接用php index.php

**Comment by xxhh283** [comment]
emmmmm
好的，是我的锅
