### ISSUE TITLE
能否添加双端抽奖功能和应援团签到功能

### ISSUE THREAD

**Issue by Franinc** [lkeme/BiliHelper#8]
双端抽奖功能指的是活动在双端都能抽奖，虽然最后奖品仍然是两根辣条但其中一端（可能是客户端）在点抽奖时能多获得一根辣条，也就是说一次能获得三根辣条，收益增加50%。
主播的应援团签到每次能给勋章加10亲密度，加十个应援团每次共能获得100亲密度（相当于100辣条了），不清楚一天能否多次签到
两个功能是隔壁基于node.js实现的那个，不过armel架构装不了8.x版本的node.js

**Comment by lkeme** [comment]
@Franinc 主播应援团签到有这个计划，
另外关于双端抽奖，我没测试过是否能双端同时抽奖，
我会去测试一下，如果可以的话，应该会添加的，

**Comment by lkeme** [comment]
@Franinc 已添加双端抽奖和应援团签到，你可以测试一下
