### ISSUE TITLE
硬币兑换失败，发送弹幕功能开启后貌似没运行

### ISSUE THREAD

**Issue by T-Evan** [lkeme/BiliHelper#9]
![image](https://user-images.githubusercontent.com/16934582/37455453-130a4e00-2878-11e8-94d7-6cbe83950f80.png)
![image](https://user-images.githubusercontent.com/16934582/37455518-39eef2aa-2878-11e8-9ec3-3c514d73f88b.png)
btw，分别在index.php和includes/Bilibili.php里设置了同一个房间号，在这个房间不直播的情况下仍然在日志里看到弹幕和礼物的发送信息是为什么呀

**Comment by lkeme** [comment]
@tangmingshuai  硬币兑换应该修好了，

发送弹幕的房间是 $_privateSendMsgInfo里面的roomid

index和Bilibili里面的roomid是投喂过期礼物的

弹幕消息和礼物是随机的房间，并不是你设置的房间

**Comment by T-Evan** [comment]
thks，发送弹幕房间支持指定多个嘛

**Comment by T-Evan** [comment]
测试发现未直播房间弹幕发送正常，直播中的房间自动发送弹幕失败qaq

**Comment by lkeme** [comment]
@tangmingshuai 还有这种情况？不会这样吧，发送弹幕的API就一个，

暂时么有想做多房间

**Comment by T-Evan** [comment]
我又试了下，貌似就一个房间用不了，很迷哈哈，不管了

**Comment by T-Evan** [comment]
可以正常使用了，感谢
